import "./global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";

import { Toaster } from "sonner";
import { ProgressBarPleas } from "@/components/progress-bar";
import { DrawerProvider } from "@/components/providers/drawer-provider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Rick and Morty App",
  description: "Generated by create next app",
  // manifest: "/manifest.json",
  keywords: ["Rick", "Morty", "Rick and Morty", "next14", "pwa", "next-pwa"],
  themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#fff" }],
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    // { rel: "usm-icon", url: "/public/icon-128x128.png" },
    // { rel: "icon", url: "/public/icon-128x128.png" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={cn(inter.className, "bg-[#F2F3F5] dark:bg-[#313338]")}>
        {" "}
        <ProgressBarPleas />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="rickandmorty-theme"
        >
          <Toaster richColors position="bottom-right" />

          <DrawerProvider>{children}</DrawerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
